server:
  port: 8079
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,log4j2,wall
      initial-size: 2
      min-idle: 2
      max-active: 10
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.svg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        login-username: root
        login-password: 123456
        allow: 127.0.0.1
shiro:
  loginUrl: /login
  sessionManager:
    sessionIdUrlRewritingEnabled: false
mybatis:
  type-aliases-package: org.example.springboot05shiro.pojo
  mapper-locations: classpath*:sqlMapper/*.xml
  configuration:
    map-underscore-to-camel-case: true